app = "flask-htmx-alpine"
primary_region = "iad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  FLASK_ENV = "production"
  PORT = "8080"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512