services:
  - name: flask-htmx-alpine
    type: web
    build:
      type: docker
      dockerfile: Dockerfile
    ports:
      - port: 8080
        protocol: http
    env:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "8080"
    health_check:
      http:
        path: /health
        port: 8080
      grace_period_seconds: 60
      interval_seconds: 30
      timeout_seconds: 10
    scaling:
      min: 1
      max: 1
    regions:
      - fra
    instance_type: nano